### ISSUE TITLE
[Bug] No "alpha" variable inside LSTM class

### ISSUE THREAD

**Issue by dyngts** [Zozoz/TD-LSTM#2]
Hi @Zozoz,

I think there is syntax error when call self.alpha which not defined in LSTM class init (i'm using at_lstm.py). I have no idea to solve it. Can you look for that? Thank you!

**Comment by Zozoz** [comment]
I update our code to tensorflow 1.0 and fix this bug!

**Comment by dyngts** [comment]
Thanks sir!
