### ISSUE TITLE
Task Definition

### ISSUE THREAD

**Issue by dyngts** [Zozoz/TD-LSTM#3]
Hi @Zozoz,

I would like to ask about task definition for the code at_lstm.py. Is it only classify the polarity of sentiment (pos, neg, neut) or also extract the aspects like defined on the paper?

Thank you.

**Comment by Zozoz** [comment]
We focus on predicting the polarity of a sentence with an aspect, and aspects are input as priori information.

**Comment by dyngts** [comment]
I see, thank you for the confirmation @Zozoz
